# Generated by Django 5.2.7 on 2025-11-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã ngân hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_transaction_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch ngân hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch'),
        ),
    ]
