# Generated by Django 5.2.7 on 2025-11-09 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá hiện tại')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá cũ')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='Đơn vị tính')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá trung bình')),
                ('reviews_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượt đánh giá')),
                ('sold_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng đã bán')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('detail_description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Hình ảnh chính')),
                ('images', models.TextField(blank=True, help_text='JSON array of image URLs', verbose_name='Hình ảnh phụ')),
                ('specifications', models.TextField(blank=True, help_text='JSON object with specifications', verbose_name='Thông số kỹ thuật')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='Xuất xứ')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Trọng lượng')),
                ('preservation', models.CharField(blank=True, max_length=200, verbose_name='Cách bảo quản')),
                ('expiry', models.CharField(blank=True, max_length=200, verbose_name='Hạn sử dụng')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='Chứng nhận')),
                ('status', models.CharField(choices=[('active', 'Đang bán'), ('out_of_stock', 'Hết hàng'), ('inactive', 'Ngừng bán')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Hình ảnh')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'db_table': 'product_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_categor_29e98f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-created_at'], name='products_status_7a594e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
    ]
