# Generated by Django 5.2.7 on 2025-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Đang bán'), ('inactive', 'Ngừng bán')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
