# Generated by Django 5.2.7 on 2025-11-12 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_remove_product_is_featured_alter_product_status'),
        ('reviews', '0002_remove_reviewimage_review_delete_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)')),
                ('comment', models.TextField(help_text='Chia sẻ trải nghiệm của bạn về sản phẩm', verbose_name='Nhận xét')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Hình ảnh đánh giá')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Đã xác minh mua hàng')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Số lượt hữu ích')),
                ('reply', models.TextField(blank=True, verbose_name='Phản hồi từ shop')),
                ('reply_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='reviews_product_500bf4_idx'), models.Index(fields=['user', '-created_at'], name='reviews_user_id_9f7b05_idx'), models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx')],
                'unique_together': {('user', 'product', 'order')},
            },
        ),
    ]
