# Generated by Django 5.2.7 on 2025-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('seller', 'Người bán'), ('admin', 'Quản trị viên')], default='customer', max_length=20, verbose_name='Vai trò'),
        ),
    ]
